export function uwufy(text: string): string {
  // trim extra spaces, convert to lowercase, split up the words, translate each word individually then join them back together via spaces
  return text
    .trim()
    .toLowerCase()
    .split(/ +/g)
    .map((word) => {
      let punctuations = ['.', ',', '!', '?', ':', ';', '-', '+', '=', '\"', "'", '\n']

      if (word.includes('\n')) return uwufy(word.replace(/\n/g, ' ')).replace(/ /g, '\n') // translate words with \n seperately
      if (uwuDictionary[word as Word]) return uwuDictionary[word as Word]

      if (punctuations.some((symbol) => word.startsWith(symbol)))
        return word.slice(0, 1) + uwufy(word.slice(1)) // translate word ignoring the punctuation character at the beginning
      if (punctuations.some((symbol) => word.endsWith(symbol)))
        return uwufy(word.slice(0, -1)) + word.slice(-1) // translate word ignoring the punctuation character at the end

      if (word.endsWith('er')) word = word.slice(0, -2) + 'a'
      if (word.endsWith('ing')) word = word.slice(0, -3) + 'in'
      if (word.endsWith('ly')) word = word.slice(0, -2) + 'wi'
      if (word.endsWith('ck')) word = word.slice(0, -2) + 'k'
      if (word.endsWith('cky')) word = word.slice(0, -3) + 'ky'
      if (word.endsWith('cking')) word = word.slice(0, -5) + 'kin'
      if (word.endsWith('cked')) word = word.slice(0, -4) + 'kd'

      if (word.includes('ee')) word = word.replace(/ee/g, 'ii')
      if (word.includes('oo')) word = word.replace(/oo/g, 'uu')
      if (word.includes('th')) word = word.replace(/th/g, 'd')
      return word.replace(/[rl]/g, 'w')
    })
    .join(' ')
}

export type Word = keyof typeof uwuDictionary

export const uwuDictionary = {
  komimau: 'komimau',
  luxmiyu: 'luxy boo',
  lux: 'luxy boo',
  miyu: 'miyuwu',
  miyuna: 'miyuwuna',
  erik: 'baka ewik',
  erik64: 'baka ewik64',
  mod: 'mod',
  staff: 'stafu',
  ban: 'b-ban',
  kick: 'k-kick',
  hentai: 'h-h-hentai >///<',
  anime: 'animu',
  loli: 'fine lady',
  boob: 'bob',
  boobs: 'booba',
  dick: 'd-dik',
  cock: 'cok',
  penis: 'peepee',
  vagina: 'vagene',
  pp: 'piipii',
  ecchi: 'e-ecchi no koto qq',
  japanese: 'nihongo',
  japan: 'nihon',
  role: 'rol',
  awa: 'AwA',
  ewe: 'EwE',
  iwi: 'IwI',
  owo: 'OwO',
  uwu: 'UwU',
  weeb: 'wiib',
  ayaya: 'AYAYAGUN',
  lowercase: 'lowacase',
  uppercase: 'uppacase',
  capital: 'aaaa',
  capitalize: 'aaaa',
  capitals: 'aaaa',
  baka: 'b-baka',
  idiot: 'i-idiot',
  stupid: 'b-baka',
  moron: 'b-baka',
  asshole: 'butthol',
  ass: 'b-butt',
  gay: 'gae boi',
  lesbian: 'gae girl',
  dumb: 'dum dum',
  fuck: 'fak',
  "it's": 'it',
  "they're": "thei're",
  "you're": "uwu're",
  hi: 'hai',
  money: 'moonies',
  '727': 'funi numba',
  funny: 'funi',
  lucky: 'lucki',
  osu: 'oss',
  "i'm": 'me iz',
  "what's": 'wat iz',
  "what're": 'wat awe',
  tf: 'da fak',
  wtf: 'wat da fak',
  wants: 'wans',
  girl: 'giwl',
  girls: 'giwls',
  boys: 'bois',
  enough: 'enuff',
  nice: 'naisu',
  sex: 'suisex',
  oh: 'o',
  am: 'iz',
  "that's": 'dat iz',
  "how's": 'haw iz',
  "how're": 'haw aw',
  "you've": 'uwu hav',
  text: 'tex',

  the: 'da',
  of: 'ob',
  to: '2',
  and: 'an',
  a: 'a',
  in: 'in',
  is: 'iz',
  it: 'it',
  you: 'uwu',
  that: 'dat',
  he: 'he',
  was: 'was',
  for: 'fo',
  on: 'on',
  are: 'aw',
  with: 'wiz',
  as: 'as',
  i: 'me',
  his: 'his',
  they: 'thei',
  be: 'be',
  at: 'at',
  one: 'wan',
  have: 'hav',
  this: 'dis',
  from: 'from',
  or: 'ob',
  had: 'had',
  by: 'bi',
  hot: 'hot',
  but: 'butt',
  some: 'som',
  what: 'wat',
  there: 'der',
  we: 'we',
  can: 'can',
  out: 'out',
  other: 'otha',
  were: 'wer',
  all: 'all',
  your: 'uwu',
  when: 'wen',
  up: 'up',
  use: 'use',
  word: 'wowd',
  how: 'haw',
  said: 'said',
  an: 'an',
  each: 'each',
  she: 'she',
  which: 'wich',
  do: 'du',
  their: 'theiw',
  time: 'tim',
  if: 'if',
  will: 'wiww',
  way: 'wae',
  about: 'about',
  many: 'mani',
  then: 'den',
  them: 'dem',
  would: 'wud',
  write: 'wite',
  like: 'wike',
  so: 'so',
  these: 'deez',
  her: 'her',
  long: 'lon',
  make: 'mek',
  thing: 'thingy',
  see: 'see',
  him: 'him',
  two: 'two',
  has: 'has',
  look: 'look',
  more: 'moa',
  day: 'day',
  could: 'cuwd',
  go: 'go',
  come: 'com',
  did: 'did',
  my: 'mai',
  sound: 'sound',
  no: 'no',
  most: 'most',
  number: 'numba',
  who: 'who',
  over: 'ova',
  know: 'know',
  water: 'wata',
  than: 'than',
  call: 'caww',
  first: 'fiwst',
  people: 'peepo',
  may: 'may',
  down: 'down',
  side: 'side',
  been: 'bin',
  now: 'now',
  find: 'find',
  any: 'ani',
  new: 'new',
  work: 'wowk',
  part: 'pawt',
  take: 'take',
  get: 'get',
  place: 'pwace',
  made: 'made',
  live: 'wive',
  where: 'wer',
  after: 'afta',
  back: 'bacc',
  little: 'wittwe',
  only: 'onwy',
  round: 'round',
  man: 'man',
  year: 'yeaw',
  came: 'came',
  show: 'show',
  every: 'evwy',
  good: 'gud',
  me: 'me',
  give: 'gib',
  our: 'ouw',
  under: 'unda',
  name: 'name',
  very: 'vewy',
  through: 'thwu',
  just: 'just',
  form: 'fowm',
  much: 'much',
  great: 'gweat',
  think: 'thinkb',
  say: 'say',
  help: 'hewp',
  low: 'lo',
  line: 'wine',
  before: 'befow',
  turn: 'tuwn',
  cause: 'cause',
  same: 'same',
  mean: 'mean',
  differ: 'diffa',
  move: 'muv',
  right: 'wight',
  boy: 'boi',
  old: 'old',
  too: '2',
  does: 'does',
  tell: 'teww',
  sentence: 'sentens',
  set: 'set',
  three: 'thwee',
  want: 'wan',
  air: 'aiw',
  well: 'weww',
  also: 'awso',
  play: 'pway',
  small: 'smol',
  end: 'end',
  put: 'put',
  home: 'hom',
  read: 'wead',
  hand: 'hand',
  port: 'powt',
  large: 'lawge',
  spell: 'speww',
  add: 'add',
  even: 'even',
  land: 'land',
  here: 'hewe',
  must: 'must',
  big: 'big',
  high: 'hi',
  such: 'such',
  follow: 'fowwow',
  act: 'act',
  why: 'wai',
  ask: 'ask',
  men: 'bois',
  change: 'change',
  went: 'went',
  light: 'wight',
  kind: 'kind',
  off: 'obb',
  need: 'need',
  house: 'house',
  picture: 'pictuwe',
  try: 'twy',
  us: 'us',
  again: 'again',
  animal: 'animaw',
  point: 'point',
  mother: 'motha',
  world: 'warudo',
  near: 'neaw',
  build: 'buiwd',
  self: 'sewf',
  earth: 'eawth',
  father: 'fatha',
  "don't": 'don',
  head: 'hed',
}

export {}
