import { type Bang } from './bang'

export const customBangs: Bang[] = [
  {
    c: 'Entertainment',
    d: 'luxmiyu.com',
    r: 0,
    s: 'luxmiyu',
    sc: 'Search',
    t: 'luxmiyu',
    u: 'https://luxmiyu.com/search?q={{{s}}}',
  },
  {
    c: 'Entertainment',
    d: 'dcag.art',
    r: 0,
    s: 'Daily Cute Anime Girl',
    sc: 'Search',
    t: 'dcag',
    u: 'https://dcag.art/search?q={{{s}}}',
  },
  {
    c: 'Entertainment',
    d: 'osu.ppy.sh',
    r: 0,
    s: 'osu! beatmaps',
    sc: 'Games (general)',
    t: 'osub',
    u: 'https://osu.ppy.sh/beatmapsets?q={{{s}}}',
  },
  {
    c: 'Multimedia',
    d: 'danbooru.donmai.us',
    r: 0,
    s: 'Danbooru (All)',
    sc: 'Images',
    t: 'booru',
    u: 'https://danbooru.donmai.us/posts?tags={{{s}}}',
  },
  {
    c: 'Multimedia',
    d: 'rule34.xxx',
    r: 0,
    s: 'Rule 34',
    sc: 'Images',
    t: 'r34',
    u: 'https://rule34.xxx/index.php?page=post&s=list&tags={{{s}}}',
  },
  {
    c: 'Entertainment',
    d: 'ch.tetr.io',
    r: 0,
    s: 'TETR.IO User Page',
    sc: 'Games (general)',
    t: 'teto',
    u: 'https://ch.tetr.io/u/{{{s}}}',
  },
  {
    c: 'Entertainment',
    d: 'vndb.org',
    r: 292,
    s: 'Visual Novel Database (Visual Novels)',
    sc: 'Misc',
    t: 'vn',
    u: 'https://vndb.org/v?q={{{s}}}',
  },
  {
    c: 'Entertainment',
    d: 'vndb.org',
    r: 292,
    s: 'Visual Novel Database (Releases)',
    sc: 'Misc',
    t: 'vndbr',
    u: 'https://vndb.org/r?q={{{s}}}',
  },
  {
    c: 'Entertainment',
    d: 'vndb.org',
    r: 292,
    s: 'Visual Novel Database (Producers)',
    sc: 'Misc',
    t: 'vndbp',
    u: 'https://vndb.org/p?q={{{s}}}',
  },
  {
    c: 'Entertainment',
    d: 'vndb.org',
    r: 292,
    s: 'Visual Novel Database (Staff)',
    sc: 'Misc',
    t: 'vndbs',
    u: 'https://vndb.org/s?q={{{s}}}',
  },
  {
    c: 'Entertainment',
    d: 'vndb.org',
    r: 292,
    s: 'Visual Novel Database (Tags)',
    sc: 'Misc',
    t: 'vndbt',
    u: 'https://vndb.org/g/list?q={{{s}}}',
  },
]
