import { type Bang } from './bang'

export const customBangs: Bang[] = [
  {
    c: 'Entertainment',
    d: 'luxmiyu.com',
    r: 0,
    s: 'luxmiyu',
    sc: 'Search',
    t: 'luxmiyu',
    u: 'https://luxmiyu.com/search?q={{{s}}}',
  },
  {
    c: 'Entertainment',
    d: 'dcag.art',
    r: 0,
    s: 'Daily Cute Anime Girl',
    sc: 'Search',
    t: 'dcag',
    u: 'https://dcag.art/search?q={{{s}}}',
  },
  {
    c: 'Entertainment',
    d: 'osu.ppy.sh',
    r: 0,
    s: 'osu! beatmaps',
    sc: 'Games (general)',
    t: 'osub',
    u: 'https://osu.ppy.sh/beatmapsets?q={{{s}}}',
  },
  {
    c: 'Multimedia',
    d: 'danbooru.donmai.us',
    r: 0,
    s: 'Danbooru (All)',
    sc: 'Images',
    t: 'booru',
    u: 'https://danbooru.donmai.us/posts?tags={{{s}}}',
  },
  {
    c: 'Multimedia',
    d: 'rule34.xxx',
    r: 0,
    s: 'Rule 34',
    sc: 'Images',
    t: 'r34',
    u: 'https://rule34.xxx/index.php?page=post&s=list&tags={{{s}}}',
  },
  {
    c: 'Entertainment',
    d: 'ch.tetr.io',
    r: 0,
    s: 'TETR.IO User Page',
    sc: 'Games (general)',
    t: 'teto',
    u: 'https://ch.tetr.io/u/{{{s}}}',
  },
  {
    c: 'Entertainment',
    d: 'vndb.org',
    r: 0,
    s: 'Visual Novel Database (Visual Novels)',
    sc: 'Misc',
    t: 'vn',
    u: 'https://vndb.org/v?q={{{s}}}',
  },
  {
    c: 'Entertainment',
    d: 'vndb.org',
    r: 0,
    s: 'Visual Novel Database (Releases)',
    sc: 'Misc',
    t: 'vndbr',
    u: 'https://vndb.org/r?q={{{s}}}',
  },
  {
    c: 'Entertainment',
    d: 'vndb.org',
    r: 0,
    s: 'Visual Novel Database (Producers)',
    sc: 'Misc',
    t: 'vndbp',
    u: 'https://vndb.org/p?q={{{s}}}',
  },
  {
    c: 'Entertainment',
    d: 'vndb.org',
    r: 0,
    s: 'Visual Novel Database (Staff)',
    sc: 'Misc',
    t: 'vndbs',
    u: 'https://vndb.org/s?q={{{s}}}',
  },
  {
    c: 'Entertainment',
    d: 'vndb.org',
    r: 0,
    s: 'Visual Novel Database (Tags)',
    sc: 'Misc',
    t: 'vndbt',
    u: 'https://vndb.org/g/list?q={{{s}}}',
  },
  {
    c: 'Entertainment',
    d: 'www.ryuugames.com',
    r: 0,
    s: 'Ryuugames',
    sc: 'Misc',
    t: 'ryuu',
    u: 'https://www.ryuugames.com/?s={{{s}}}',
  },
  {
    c: 'Entertainment',
    d: 'kemono.su',
    r: 0,
    s: 'Kemono',
    sc: 'Misc',
    t: 'kmn',
    u: 'https://kemono.su/artists?q={{{s}}}',
  },
  {
    c: 'Entertainment',
    d: 'coomer.su',
    r: 0,
    s: 'Coomer',
    sc: 'Misc',
    t: 'cmr',
    u: 'https://coomer.su/artists?q={{{s}}}',
  },
  {
    c: 'Entertainment',
    d: 'nhentai.net',
    r: 0,
    s: 'Nhentai',
    sc: 'Misc',
    t: 'nhentai',
    u: 'https://nhentai.net/search/?q={{{s}}}',
  },
  {
    c: 'Entertainment',
    d: 'e-hentai.org',
    r: 0,
    s: 'E-Hentai Galleries',
    sc: 'Misc',
    t: 'ehentai',
    u: 'https://e-hentai.org/?f_search={{{s}}}',
  },
  {
    c: 'Entertainment',
    d: 'www.fanbox.cc',
    r: 0,
    s: 'FANBOX (Creators)',
    sc: 'Misc',
    t: 'fanbox',
    u: 'https://www.fanbox.cc/search?type=creator&q={{{s}}}',
  },
  {
    c: 'Entertainment',
    d: 'www.fanbox.cc',
    r: 0,
    s: 'FANBOX (Tags)',
    sc: 'Misc',
    t: 'fanboxt',
    u: 'https://www.fanbox.cc/search?type=tag&q={{{s}}}',
  },
  {
    c: 'Entertainment',
    d: 'www.patreon.com',
    r: 0,
    s: 'Patreon (Creators)',
    sc: 'Misc',
    t: 'patreonc',
    u: 'https://www.patreon.com/explore/search?type=campaign&query={{{s}}}',
  },
  {
    c: 'Entertainment',
    d: 'dpm.lol',
    r: 0,
    s: 'DPM.LOL (Champion Builds)',
    sc: 'Games (general)',
    t: 'dpm',
    u: 'https://dpm.lol/champions/{{{s}}}/build',
  },
  {
    c: 'Entertainment',
    d: 'mapgenie.io',
    r: 0,
    s: 'Mapgenie (Escape from Tarkov)',
    sc: 'Games (general)',
    t: 'mapg',
    u: 'https://mapgenie.io/tarkov/maps/{{{s}}}',
  },
  {
    c: 'Entertainment',
    d: 'mapgenie.io',
    r: 0,
    s: 'Mapgenie (Escape from Tarkov)',
    sc: 'Games (general)',
    t: 'mapgenie',
    u: 'https://mapgenie.io/tarkov/maps/{{{s}}}',
  },
]
